let thuongHieu1 = { maThuongHieu: 1, tenThuongHieu: "Chanel", link: "https://www.chanel.com/vn/" };
let thuongHieu2 = { maThuongHieu: 2, tenThuongHieu: "Hermèss", link: "https://www.hermes.com/us/en/" };
let thuongHieu3 = { maThuongHieu: 3, tenThuongHieu: "Gucci", link: "https://www.gucci.com/vn/" };
let thuongHieu4 = { maThuongHieu: 4, tenThuongHieu: "Louis Vuittion", link: "https://us.louisvuitton.com/eng-us/homepage?campaign=b_google%2Fstorepage" };
let thuongHieu5 = { maThuongHieu: 5, tenThuongHieu: "Prada", link: "https://www.prada.com/vn/" };
let thuongHieu6 = { maThuongHieu: 6, tenThuongHieu: "Dior", link: "https://www.dior.com/en_us?gclid=CjwKCAjw682TBhATEiwA9crl3x4qixHR-egQTNO7lLSzRJshaMiowA1tmvys2k30fTz6jk5s_t-snBoC7CMQAvD_BwE" };
let thuongHieu7 = { maThuongHieu: 7, tenThuongHieu: "Burberry", link: "https://www.burberry.com/vn/" };

let dsThuongHieu = [thuongHieu1, thuongHieu2, thuongHieu3, thuongHieu4, thuongHieu5, thuongHieu6, thuongHieu7];
localStorage.setItem("dsThuongHieu", JSON.stringify(dsThuongHieu));

let tintuc1 = { matt: 1, tieuDe: "Ciza thay đổi phong cách thương hiệu", noiDung: "Thương hiệu Ciza dần chuyển hướng sang phong cách thời trang thể thao để đến gần hơn với khách hàng mục tiêu.", ngaydang: "Thứ sáu, 22/4/2022, 08:00 (GMT+7)", link: "https://vnexpress.net/ciza-thay-doi-phong-cach-thuong-hieu-4449049.html", hinhAnh: "../img/imgTinTuc/img-TT1.jpg" };
let tintuc2 = { matt: 2, tieuDe: "Aristino khai trương chuỗi cửa hàng mới", noiDung: "Thương hiệu thời trang nam Aristino khai trương ba cửa hàng mới, chạm mốc 65 cơ sở trên toàn quốc từ ngày 9/4.", ngaydang: "Thứ năm, 14/4/2022, 12:00 (GMT+7)", link: "https://vnexpress.net/thuong-hieu-aristino-khai-truong-chuoi-cua-hang-moi-4451015.html", hinhAnh: "../img/imgTinTuc/img-TT2.jpg" };
let tintuc3 = { matt: 3, tieuDe: "Thời trang nam giảm giá 50% hôm nay trên Shop VnExpress", noiDung: "Thương hiệu thời trang nam Aristino khai trương ba cửa hàng mới, chạm mốc 65 cơ sở trên toàn quốc từ ngày 9/4.", ngaydang: "Thứ năm, 14/4/2022, 12:00 (GMT+7)", link: "https://vnexpress.net/thuong-hieu-aristino-khai-truong-chuoi-cua-hang-moi-4451015.html", hinhAnh: "../img/imgTinTuc/img-TT3.jpg" };
let tintuc4 = { matt: 4, tieuDe: "HappyHow 'biến nguy thành cơ' trong đại dịch", noiDung: "Thương hiệu HappyHow vượt qua ảnh hưởng của Covid-19 kết hợp xu hướng O2O (online-to-offline) và công nghệ.", ngaydang: "Thứ sáu, 18/2/2022, 08:00 (GMT+7)", link: "https://vnexpress.net/happyhow-bien-nguy-thanh-co-trong-dai-dich-4427970.html", hinhAnh: "../img/imgTinTuc/img-TT4.jpg" };
let tintuc5 = { matt: 5, tieuDe: "Áo cắt xẻ, váy cho đàn ông lên ngôi ở Xuân Hè 2022", noiDung: "Váy, trang phục cut-out vào nhóm xu hướng nổi bật dành cho nam giới nửa đầu năm nay.", ngaydang: "Thứ sáu, 14/1/2022, 13:46 (GMT+7)", link: "https://vnexpress.net/ao-cat-xe-vay-cho-dan-ong-len-ngoi-o-xuan-he-2022-4416260.html", hinhAnh: "../img/imgTinTuc/img-TT5.jpg" };
let tintuc6 = { matt: 6, tieuDe: "Đàn ông Italy đọ phong cách ở lễ hội thời trang", noiDung: "Các chàng trai, quý ông chưng diện đa phong cách trong lễ hội thời trang Pitti Uomo ở Iltay.", ngaydang: "Thứ năm, 13/1/2022, 12:54 (GMT+7)", link: "https://vnexpress.net/dan-ong-italy-do-phong-cach-o-le-hoi-thoi-trang-4415761.html", hinhAnh: "../img/imgTinTuc/img-TT6.jpg" };
let tintuc7 = { matt: 7, tieuDe: "Loạt sản phẩm nam đồng giảm 50%", noiDung: "Giày da nam, đồng hồ nam của Pierre Cardin, thắt lưng Oscar chính hãng đang bán đồng mức ưu đãi 50% trên Shop. ", ngaydang: "Thứ sáu, 19/11/2021, 14:00 (GMT+7)", link: "https://vnexpress.net/loat-san-pham-thoi-trang-hang-hieu-nam-dong-giam-50-4388277.html", hinhAnh: "../img/imgTinTuc/img-TT7.jpg" };
let tintuc8 = { matt: 8, tieuDe: "Mốt giày búp bê dành cho đàn ông.", noiDung: "Molly Goddard, Maison Margiela... lăng xê những đôi búp bê nữ tính dành cho cánh mày râu.", ngaydang: "Thứ hai, 1/11/2021, 21:36 (GMT+7)", link: "https://vnexpress.net/mot-giay-bup-be-danh-cho-dan-ong-4379798.html", hinhAnh: "../img/imgTinTuc/img-TT8.jpg" };
let tintuc9 = { matt: 9, tieuDe: "Vì sao ngày càng nhiều nam giới mặc váy.", noiDung: "Ngày càng nhiều nam giới ở châu Âu tìm mua váy, đồng thời bảo vệ quan điểm: thời trang không phân biệt giới tính.", ngaydang: "Thứ năm, 9/9/2021, 05:00 (GMT+7)", link: "https://vnexpress.net/vi-sao-ngay-cang-nhieu-nam-gioi-mac-vay-4353121.html", hinhAnh: "../img/imgTinTuc/img-TT9.jpg" };
let tintuc10 = { matt: 10, tieuDe: "Đàn ông theo đuổi mốt mặc hở khoe cơ thể.", noiDung: "Trang phục cắt xẻ lộ da thịt được nhiều chàng trai ưa chuộng ở các tuần thời trang Xuân Hè 2022.", ngaydang: "Thứ sáu, 2/7/2021, 13:30 (GMT+7)", link: "https://vnexpress.net/dan-ong-theo-duoi-mot-mac-ho-4303215.html", hinhAnh: "../img/imgTinTuc/img-TT10.jpg" };
let tintuc11 = { matt: 11, tieuDe: "Street style của nam giới ở Paris Fashion Week.", noiDung: "Nhiều chàng trai phối đồ đầy màu sắc khi thể hiện phong cách ở Tuần lễ thời trang Paris.", ngaydang: "Thứ sáu, 25/6/2021, 13:30 (GMT+7)", link: "https://vnexpress.net/street-style-cua-nam-gioi-o-paris-fashion-week-4299318.html", hinhAnh: "../img/imgTinTuc/img-TT11.jpg" };
let tintuc12 = { matt: 12, tieuDe: "Routine mở liên tiếp hai cửa hàng mới giữa dịch Covid-19", noiDung: "Thương hiệu thời trang Việt Nam không chỉ đầu tư thiết kế hai cửa hàng lớn mà còn ra mắt dòng sản phẩm mới cho nữ giới.", ngaydang: "Thứ bảy, 13/3/2021, 09:00 (GMT+7)", link: "https://vnexpress.net/routine-mo-lien-tiep-hai-cua-hang-moi-giua-dich-covid-19-4247007.html", hinhAnh: "../img/imgTinTuc/img-TT12.jpg" };
let tintuc13 = { matt: 13, tieuDe: "Món đồ thời trang nam bán giá ưu đãi.", noiDung: "Đồng hồ, mắt kính, áo khoác, thắt lưng... có giá giảm đến 50%, còn từ 188.000 đồng đến 1,56 triệu đồng trên Shop. ", ngaydang: "Thứ ba, 9/3/2021, 12:00 (GMT+7)", link: "https://vnexpress.net/nhung-mon-do-thoi-trang-nam-ban-gia-uu-dai-4244927.html", hinhAnh: "../img/imgTinTuc/img-TT13.jpg" };
let tintuc14 = { matt: 14, tieuDe: "Sơ mi công sở cho nam", noiDung: "Áo sơ mi tay ngắn hoặc dài, màu sắc trang nhã, giúp phái mạnh thanh lịch chốn công sở hoặc khi gặp gỡ đối tác. ", ngaydang: "Thứ tư, 4/11/2020, 15:14 (GMT+7)", link: "https://vnexpress.net/so-mi-cong-so-cho-nam-4186777.html", hinhAnh: "../img/imgTinTuc/img-TT14.jpg" };
let tintuc15 = { matt: 15, tieuDe: "Hermes lăng xê đồ tối giản", noiDung: "Hermes đưa phong cách tối giản, chuẩn mực vào bộ sưu tập Xuân Hè 2021 dành cho nam. ", ngaydang: "Thứ ba, 7/7/2020, 19:00 (GMT+7)", link: "https://vnexpress.net/hermes-lang-xe-do-toi-gian-4126766.html", hinhAnh: "../img/imgTinTuc/img-TT15.jpg" };

let dsTinTuc = [tintuc1, tintuc2, tintuc3, tintuc4, tintuc5, tintuc6, tintuc7, tintuc8, tintuc9, tintuc10, tintuc11, tintuc12, tintuc13, tintuc14, tintuc15];

localStorage.setItem("dsTinTuc", JSON.stringify(dsTinTuc));